#!/bin/bash

HOSTNAME=$(hostname)
DISTRO=$(grep '^NAME=' /etc/os-release | cut -d '=' -f2 | tr -d '"')
DISTRO_VERSION=$(grep '^VERSION=' /etc/os-release | cut -d '=' -f2 | tr -d '"')
UPTIME=$(uptime -p)

CPU=$(lscpu | grep 'Model name' | cut -d ':' -f2 | sed 's/^[[:space:]]*//')
RAM=$(free -h | grep 'Mem' | awk '{print $2}')
DISK=$(lsblk -o NAME,SIZE,MODEL -d | grep -v "NAME" | tr -s ' ' | cut -d ' ' -f2,3)
VIDEO=$(lspci | grep VGA | cut -d ':' -f3 | sed 's/^[[:space:]]*//')

FQDN=$(hostname -f)
IP_ADDR=$(ip a | grep -A 2 'default' | grep inet | awk '{print $2}' | cut -d '/' -f1)
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep 'nameserver' | awk '{print $2}')

USERS=$(who | awk '{print $1}' | tr '\n' ', ' | sed 's/, $//')
DISK_SPACE=$(df -h / | awk 'NR==2 {print $4}')
PROCESS_COUNT=$(ps aux --no-heading | wc -l)
LOAD_AVERAGE=$(uptime | cut -d ' ' -f9-11)
LISTENING_PORTS=$(ss -tuln | grep LISTEN | wc -l)
UFW_STATUS=$(sudo ufw status | head -n 2 | tail -n 1)

cat <<EOF

System Report generated by $USER, $(date)

System Information
------------------
Hostname: $HOSTNAME
OS: $DISTRO $DISTRO_VERSION
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
RAM: $RAM
Disk(s): $DISK
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $IP_ADDR
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGE
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF

